const imageData: {
  category: string;
  src: string;
  alt: string;
  width: number;
  height: number;
}[] = [
  {
    category: 'children',
    src: 'children/children-1.jpg',
    alt: 'children-1',
    width: 2400,
    height: 1600,
  },
  {
    category: 'children',
    src: 'children/children-10.jpg',
    alt: 'children-10',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-11.jpg',
    alt: 'children-11',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-12.jpg',
    alt: 'children-12',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-13.jpg',
    alt: 'children-13',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-14.jpg',
    alt: 'children-14',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-2.jpg',
    alt: 'children-2',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-3.jpg',
    alt: 'children-3',
    width: 561,
    height: 1024,
  },
  {
    category: 'children',
    src: 'children/children-4.jpg',
    alt: 'children-4',
    width: 6000,
    height: 4000,
  },
  {
    category: 'children',
    src: 'children/children-5.jpg',
    alt: 'children-5',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-6.jpg',
    alt: 'children-6',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-7.jpg',
    alt: 'children-7',
    width: 1600,
    height: 2400,
  },
  {
    category: 'children',
    src: 'children/children-8.jpg',
    alt: 'children-8',
    width: 4000,
    height: 6000,
  },
  {
    category: 'children',
    src: 'children/children-9.jpg',
    alt: 'children-9',
    width: 6000,
    height: 4000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-1.jpg',
    alt: 'dj-coverage-1',
    width: 4000,
    height: 6000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-10.jpg',
    alt: 'dj-coverage-10',
    width: 6000,
    height: 4000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-11.jpg',
    alt: 'dj-coverage-11',
    width: 6000,
    height: 4000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-2.jpg',
    alt: 'dj-coverage-2',
    width: 4000,
    height: 6000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-3.jpg',
    alt: 'dj-coverage-3',
    width: 4000,
    height: 6000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-4.jpg',
    alt: 'dj-coverage-4',
    width: 1758,
    height: 2336,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-5.jpg',
    alt: 'dj-coverage-5',
    width: 4000,
    height: 6000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-6.jpg',
    alt: 'dj-coverage-6',
    width: 3072,
    height: 4096,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-7.jpg',
    alt: 'dj-coverage-7',
    width: 6000,
    height: 4000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-8.jpg',
    alt: 'dj-coverage-8',
    width: 6000,
    height: 4000,
  },
  {
    category: 'dj-coverage',
    src: 'dj-coverage/dj-coverage-9.jpg',
    alt: 'dj-coverage-9',
    width: 6000,
    height: 4000,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-1.jpg',
    alt: 'event-coverage-1',
    width: 4000,
    height: 6000,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-10.jpg',
    alt: 'event-coverage-10',
    width: 2400,
    height: 1600,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-11.jpg',
    alt: 'event-coverage-11',
    width: 2976,
    height: 1984,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-12.jpg',
    alt: 'event-coverage-12',
    width: 2976,
    height: 1984,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-2.jpg',
    alt: 'event-coverage-2',
    width: 4000,
    height: 6000,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-3.jpg',
    alt: 'event-coverage-3',
    width: 6000,
    height: 4000,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-4.jpg',
    alt: 'event-coverage-4',
    width: 6000,
    height: 4000,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-5.jpg',
    alt: 'event-coverage-5',
    width: 1600,
    height: 2400,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-6.jpg',
    alt: 'event-coverage-6',
    width: 2400,
    height: 1600,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-7.jpg',
    alt: 'event-coverage-7',
    width: 2976,
    height: 1984,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-8.jpg',
    alt: 'event-coverage-8',
    width: 2976,
    height: 1984,
  },
  {
    category: 'event-coverage',
    src: 'event-coverage/event-coverage-9.jpg',
    alt: 'event-coverage-9',
    width: 6000,
    height: 4000,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-1.jpg',
    alt: 'fashion-1',
    width: 1365,
    height: 2048,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-10.jpg',
    alt: 'fashion-10',
    width: 2400,
    height: 1600,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-11.jpg',
    alt: 'fashion-11',
    width: 1415,
    height: 2000,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-12.jpg',
    alt: 'fashion-12',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-13.jpg',
    alt: 'fashion-13',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-14.jpg',
    alt: 'fashion-14',
    width: 6000,
    height: 4000,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-15.jpg',
    alt: 'fashion-15',
    width: 2976,
    height: 1984,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-16.jpg',
    alt: 'fashion-16',
    width: 1984,
    height: 2976,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-17.jpg',
    alt: 'fashion-17',
    width: 2976,
    height: 1984,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-18.jpg',
    alt: 'fashion-18',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-19.jpg',
    alt: 'fashion-19',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-2.jpg',
    alt: 'fashion-2',
    width: 1600,
    height: 1685,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-20.jpg',
    alt: 'fashion-20',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-21.jpg',
    alt: 'fashion-21',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-22.jpg',
    alt: 'fashion-22',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-23.jpg',
    alt: 'fashion-23',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-24.jpg',
    alt: 'fashion-24',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-3.jpg',
    alt: 'fashion-3',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-4.jpg',
    alt: 'fashion-4',
    width: 1600,
    height: 2000,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-5.jpg',
    alt: 'fashion-5',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-6.jpg',
    alt: 'fashion-6',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-7.jpg',
    alt: 'fashion-7',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-8.jpg',
    alt: 'fashion-8',
    width: 1600,
    height: 2400,
  },
  {
    category: 'fashion',
    src: 'fashion/fashion-9.jpg',
    alt: 'fashion-9',
    width: 1600,
    height: 2400,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-1.jpg',
    alt: 'gastronomy-1',
    width: 3024,
    height: 4032,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-10.jpg',
    alt: 'gastronomy-10',
    width: 1600,
    height: 2208,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-11.jpg',
    alt: 'gastronomy-11',
    width: 1600,
    height: 2400,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-12.jpg',
    alt: 'gastronomy-12',
    width: 1600,
    height: 2400,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-2.jpg',
    alt: 'gastronomy-2',
    width: 2400,
    height: 1600,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-3.jpg',
    alt: 'gastronomy-3',
    width: 2400,
    height: 1600,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-4.jpg',
    alt: 'gastronomy-4',
    width: 2400,
    height: 1600,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-5.jpg',
    alt: 'gastronomy-5',
    width: 4000,
    height: 6000,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-6.jpg',
    alt: 'gastronomy-6',
    width: 4000,
    height: 6000,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-7.jpg',
    alt: 'gastronomy-7',
    width: 4000,
    height: 6000,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-8.jpg',
    alt: 'gastronomy-8',
    width: 4000,
    height: 6000,
  },
  {
    category: 'gastronomy',
    src: 'gastronomy/gastronomy-9.jpg',
    alt: 'gastronomy-9',
    width: 4000,
    height: 6000,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-1.jpg',
    alt: 'marriage-1',
    width: 1600,
    height: 2400,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-2.jpg',
    alt: 'marriage-2',
    width: 1600,
    height: 2400,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-3.jpg',
    alt: 'marriage-3',
    width: 1600,
    height: 2400,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-4.jpg',
    alt: 'marriage-4',
    width: 2400,
    height: 1600,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-5.jpg',
    alt: 'marriage-5',
    width: 2400,
    height: 1600,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-6.jpg',
    alt: 'marriage-6',
    width: 1600,
    height: 2400,
  },
  {
    category: 'marriage',
    src: 'marriage/marriage-7.jpg',
    alt: 'marriage-7',
    width: 2400,
    height: 1600,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-1.png',
    alt: 'music-videos-bts-1',
    width: 1179,
    height: 2087,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-10.jpg',
    alt: 'music-videos-bts-10',
    width: 744,
    height: 445,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-11.jpg',
    alt: 'music-videos-bts-11',
    width: 1200,
    height: 1600,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-13.jpg',
    alt: 'music-videos-bts-13',
    width: 683,
    height: 1024,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-14.jpg',
    alt: 'music-videos-bts-14',
    width: 683,
    height: 1024,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-15.jpg',
    alt: 'music-videos-bts-15',
    width: 6000,
    height: 4000,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-16.jpg',
    alt: 'music-videos-bts-16',
    width: 6000,
    height: 4000,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-2.png',
    alt: 'music-videos-bts-2',
    width: 1179,
    height: 2097,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-3.png',
    alt: 'music-videos-bts-3',
    width: 1179,
    height: 2023,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-4.png',
    alt: 'music-videos-bts-4',
    width: 1179,
    height: 2057,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-5.jpg',
    alt: 'music-videos-bts-5',
    width: 2400,
    height: 1600,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-6.jpg',
    alt: 'music-videos-bts-6',
    width: 2400,
    height: 1600,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-7.jpg',
    alt: 'music-videos-bts-7',
    width: 1600,
    height: 2400,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-8.png',
    alt: 'music-videos-bts-8',
    width: 1179,
    height: 2024,
  },
  {
    category: 'music-videos-bts',
    src: 'music-videos-bts/music-videos-bts-9.jpg',
    alt: 'music-videos-bts-9',
    width: 6000,
    height: 4000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-1.jpg',
    alt: 'photo-studio-1',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-10.jpg',
    alt: 'photo-studio-10',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-11.jpg',
    alt: 'photo-studio-11',
    width: 4000,
    height: 6000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-12.jpg',
    alt: 'photo-studio-12',
    width: 5125,
    height: 4000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-13.jpg',
    alt: 'photo-studio-13',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-14.jpg',
    alt: 'photo-studio-14',
    width: 4000,
    height: 6000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-15.jpg',
    alt: 'photo-studio-15',
    width: 3892,
    height: 6000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-16.jpg',
    alt: 'photo-studio-16',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-17.jpg',
    alt: 'photo-studio-17',
    width: 1600,
    height: 2000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-18.jpg',
    alt: 'photo-studio-18',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-19.jpg',
    alt: 'photo-studio-19',
    width: 2400,
    height: 1600,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-2.jpg',
    alt: 'photo-studio-2',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-20.jpg',
    alt: 'photo-studio-20',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-3.jpg',
    alt: 'photo-studio-3',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-4.jpg',
    alt: 'photo-studio-4',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-5.jpg',
    alt: 'photo-studio-5',
    width: 1984,
    height: 2976,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-6.jpg',
    alt: 'photo-studio-6',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-7.jpg',
    alt: 'photo-studio-7',
    width: 1600,
    height: 2400,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-8.jpg',
    alt: 'photo-studio-8',
    width: 4000,
    height: 6000,
  },
  {
    category: 'photo-studio',
    src: 'photo-studio/photo-studio-9.jpg',
    alt: 'photo-studio-9',
    width: 1600,
    height: 2161,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-1.jpg',
    alt: 'quinceañera-1',
    width: 6000,
    height: 4000,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-10.jpg',
    alt: 'quinceañera-10',
    width: 6000,
    height: 4000,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-11.jpg',
    alt: 'quinceañera-11',
    width: 1024,
    height: 640,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-12.jpg',
    alt: 'quinceañera-12',
    width: 2400,
    height: 1600,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-13.jpg',
    alt: 'quinceañera-13',
    width: 6000,
    height: 4000,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-14.jpg',
    alt: 'quinceañera-14',
    width: 2976,
    height: 1984,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-15.jpg',
    alt: 'quinceañera-15',
    width: 6000,
    height: 4000,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-2.jpg',
    alt: 'quinceañera-2',
    width: 1984,
    height: 2976,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-3.jpg',
    alt: 'quinceañera-3',
    width: 1600,
    height: 2400,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-4.jpg',
    alt: 'quinceañera-4',
    width: 2400,
    height: 1600,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-5.jpg',
    alt: 'quinceañera-5',
    width: 2400,
    height: 1600,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-6.jpg',
    alt: 'quinceañera-6',
    width: 2400,
    height: 1600,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-7.jpg',
    alt: 'quinceañera-7',
    width: 1600,
    height: 2400,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-8.jpg',
    alt: 'quinceañera-8',
    width: 2400,
    height: 1600,
  },
  {
    category: 'quinceañera',
    src: 'quinceañera/quinceañera-9.jpg',
    alt: 'quinceañera-9',
    width: 1600,
    height: 2400,
  },
];

export default imageData;
