const portfolioImgData: {
  category: string;
  src: string;
  alt: string;
  width: number;
  height: number;
}[] = [
  {
    category: "children",
    src: "children/children-1.jpg",
    alt: "children-1-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "children",
    src: "children/children-2.jpg",
    alt: "children-2-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-3.jpg",
    alt: "children-3-img",
    width: 561,
    height: 1024,
  },
  {
    category: "children",
    src: "children/children-4.jpg",
    alt: "children-4-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "children",
    src: "children/children-5.jpg",
    alt: "children-5-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-6.jpg",
    alt: "children-6-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-7.jpg",
    alt: "children-7-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-8.jpg",
    alt: "children-8-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "children",
    src: "children/children-9.jpg",
    alt: "children-9-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "children",
    src: "children/children-10.jpg",
    alt: "children-10-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-11.jpg",
    alt: "children-11-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-12.jpg",
    alt: "children-12-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-13.jpg",
    alt: "children-13-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "children",
    src: "children/children-14.jpg",
    alt: "children-14-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-1.jpg",
    alt: "djCoverage-1-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-2.jpg",
    alt: "djCoverage-2-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-3.jpg",
    alt: "djCoverage-3-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-4.jpg",
    alt: "djCoverage-4-img",
    width: 1758,
    height: 2336,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-5.jpg",
    alt: "djCoverage-5-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-6.jpg",
    alt: "djCoverage-6-img",
    width: 3072,
    height: 4096,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-7.jpg",
    alt: "djCoverage-7-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-8.jpg",
    alt: "djCoverage-8-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-9.jpg",
    alt: "djCoverage-9-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-10.jpg",
    alt: "djCoverage-10-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "djCoverage",
    src: "djCoverage/djCoverage-11.jpg",
    alt: "djCoverage-11-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-1.jpg",
    alt: "eventCoverage-1-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-2.jpg",
    alt: "eventCoverage-2-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-3.jpg",
    alt: "eventCoverage-3-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-4.jpg",
    alt: "eventCoverage-4-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-5.jpg",
    alt: "eventCoverage-5-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-6.jpg",
    alt: "eventCoverage-6-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-7.jpg",
    alt: "eventCoverage-7-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-8.jpg",
    alt: "eventCoverage-8-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-9.jpg",
    alt: "eventCoverage-9-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-10.jpg",
    alt: "eventCoverage-10-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage-11.jpg",
    alt: "eventCoverage-11-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "eventCoverage",
    src: "eventCoverage/eventCoverage12.jpg",
    alt: "eventCoverage12-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "fashion",
    src: "fashion/fashion-1.jpg",
    alt: "fashion-1-img",
    width: 1365,
    height: 2048,
  },
  {
    category: "fashion",
    src: "fashion/fashion-2.jpg",
    alt: "fashion-2-img",
    width: 1600,
    height: 1685,
  },
  {
    category: "fashion",
    src: "fashion/fashion-3.jpg",
    alt: "fashion-3-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-4.jpg",
    alt: "fashion-4-img",
    width: 1600,
    height: 2000,
  },
  {
    category: "fashion",
    src: "fashion/fashion-5.jpg",
    alt: "fashion-5-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-6.jpg",
    alt: "fashion-6-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-7.jpg",
    alt: "fashion-7-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-8.jpg",
    alt: "fashion-8-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-9.jpg",
    alt: "fashion-9-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-10.jpg",
    alt: "fashion-10-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "fashion",
    src: "fashion/fashion-11.jpg",
    alt: "fashion-11-img",
    width: 1415,
    height: 2000,
  },
  {
    category: "fashion",
    src: "fashion/fashion-12.jpg",
    alt: "fashion-12-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-13.jpg",
    alt: "fashion-13-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-14.jpg",
    alt: "fashion-14-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "fashion",
    src: "fashion/fashion-15.jpg",
    alt: "fashion-15-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "fashion",
    src: "fashion/fashion-16.jpg",
    alt: "fashion-16-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "fashion",
    src: "fashion/fashion-17.jpg",
    alt: "fashion-17-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "fashion",
    src: "fashion/fashion-18.jpg",
    alt: "fashion-18-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-19.jpg",
    alt: "fashion-19-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-20.jpg",
    alt: "fashion-20-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-21.jpg",
    alt: "fashion-21-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-22.jpg",
    alt: "fashion-22-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-23.jpg",
    alt: "fashion-23-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "fashion",
    src: "fashion/fashion-24.jpg",
    alt: "fashion-24-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-1.jpg",
    alt: "gastronomy-1-img",
    width: 3024,
    height: 4032,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-2.jpg",
    alt: "gastronomy-2-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-3.jpg",
    alt: "gastronomy-3-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-4.jpg",
    alt: "gastronomy-4-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-5.jpg",
    alt: "gastronomy-5-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-6.jpg",
    alt: "gastronomy-6-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-7.jpg",
    alt: "gastronomy-7-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-8.jpg",
    alt: "gastronomy-8-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-9.jpg",
    alt: "gastronomy-9-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-10.jpg",
    alt: "gastronomy-10-img",
    width: 1600,
    height: 2208,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-11.jpg",
    alt: "gastronomy-11-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "gastronomy",
    src: "gastronomy/gastronomy-12.jpg",
    alt: "gastronomy-12-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "marriage",
    src: "marriage/marriage-1.jpg",
    alt: "marriage-1-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "marriage",
    src: "marriage/marriage-2.jpg",
    alt: "marriage-2-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "marriage",
    src: "marriage/marriage-3.jpg",
    alt: "marriage-3-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "marriage",
    src: "marriage/marriage-4.jpg",
    alt: "marriage-4-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "marriage",
    src: "marriage/marriage-5.jpg",
    alt: "marriage-5-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "marriage",
    src: "marriage/marriage-6.jpg",
    alt: "marriage-6-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "marriage",
    src: "marriage/marriage-7.jpg",
    alt: "marriage-7-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-1.png",
    alt: "musicVideosBts-1-img",
    width: 1179,
    height: 2087,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-2.png",
    alt: "musicVideosBts-2-img",
    width: 1179,
    height: 2097,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-3.png",
    alt: "musicVideosBts-3-img",
    width: 1179,
    height: 2023,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-4.png",
    alt: "musicVideosBts-4-img",
    width: 1179,
    height: 2057,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-5.jpg",
    alt: "musicVideosBts-5-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-6.jpg",
    alt: "musicVideosBts-6-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-7.jpg",
    alt: "musicVideosBts-7-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-8.png",
    alt: "musicVideosBts-8-img",
    width: 1179,
    height: 2024,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-9.jpg",
    alt: "musicVideosBts-9-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-10.jpg",
    alt: "musicVideosBts-10-img",
    width: 744,
    height: 445,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-11.jpg",
    alt: "musicVideosBts-11-img",
    width: 1200,
    height: 1600,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-12.jpg",
    alt: "musicVideosBts-12-img",
    width: 4032,
    height: 3024,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-13.jpg",
    alt: "musicVideosBts-13-img",
    width: 683,
    height: 1024,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-14.jpg",
    alt: "musicVideosBts-14-img",
    width: 683,
    height: 1024,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-15.jpg",
    alt: "musicVideosBts-15-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "musicVideosBts",
    src: "musicVideosBts/musicVideosBts-16.jpg",
    alt: "musicVideosBts-16-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-1.jpg",
    alt: "personal-1-img",
    width: 1080,
    height: 1619,
  },
  {
    category: "personal",
    src: "personal/personal-2.jpg",
    alt: "personal-2-img",
    width: 683,
    height: 1024,
  },
  {
    category: "personal",
    src: "personal/personal-3.jpg",
    alt: "personal-3-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-4.jpg",
    alt: "personal-4-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-5.jpg",
    alt: "personal-5-img",
    width: 4032,
    height: 3024,
  },
  {
    category: "personal",
    src: "personal/personal-6.jpg",
    alt: "personal-6-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "personal",
    src: "personal/personal-7.jpg",
    alt: "personal-7-img",
    width: 1440,
    height: 1800,
  },
  {
    category: "personal",
    src: "personal/personal-8.jpg",
    alt: "personal-8-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "personal",
    src: "personal/personal-9.jpg",
    alt: "personal-9-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-10.jpg",
    alt: "personal-10-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-11.jpg",
    alt: "personal-11-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-12.jpg",
    alt: "personal-12-img",
    width: 1179,
    height: 2004,
  },
  {
    category: "personal",
    src: "personal/personal-13.jpg",
    alt: "personal-13-img",
    width: 1179,
    height: 2035,
  },
  {
    category: "personal",
    src: "personal/personal-14.jpg",
    alt: "personal-14-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-15.jpg",
    alt: "personal-15-img",
    width: 4000,
    height: 5760,
  },
  {
    category: "personal",
    src: "personal/personal-16.jpg",
    alt: "personal-16-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-17.jpg",
    alt: "personal-17-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-18.jpg",
    alt: "personal-18-img",
    width: 1179,
    height: 2044,
  },
  {
    category: "personal",
    src: "personal/personal-19.jpg",
    alt: "personal-19-img",
    width: 1179,
    height: 2072,
  },
  {
    category: "personal",
    src: "personal/personal-20.jpg",
    alt: "personal-20-img",
    width: 2666,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-21.jpg",
    alt: "personal-21-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "personal",
    src: "personal/personal-22.jpg",
    alt: "personal-22-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "personal",
    src: "personal/personal-23.jpg",
    alt: "personal-23-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "personal",
    src: "personal/personal-24.jpg",
    alt: "personal-24-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-25.jpg",
    alt: "personal-25-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-26.jpg",
    alt: "personal-26-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "personal",
    src: "personal/personal-27.jpg",
    alt: "personal-27-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "personal",
    src: "personal/personal-28.jpg",
    alt: "personal-28-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "personal",
    src: "personal/personal-29.jpg",
    alt: "personal-29-img",
    width: 1179,
    height: 2026,
  },
  {
    category: "personal",
    src: "personal/personal-30.jpg",
    alt: "personal-30-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "personal",
    src: "personal/personal-31.jpg",
    alt: "personal-31-img",
    width: 1440,
    height: 1440,
  },
  {
    category: "personal",
    src: "personal/personal-32.jpg",
    alt: "personal-32-img",
    width: 1365,
    height: 2048,
  },
  {
    category: "personal",
    src: "personal/personal-33.jpg",
    alt: "personal-33-img",
    width: 1365,
    height: 2048,
  },
  {
    category: "personal",
    src: "personal/personal-34.jpg",
    alt: "personal-34-img",
    width: 1365,
    height: 2048,
  },
  {
    category: "personal",
    src: "personal/personal-35.jpg",
    alt: "personal-35-img",
    width: 1365,
    height: 2048,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-1.jpg",
    alt: "photoStudio-1-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-2.jpg",
    alt: "photoStudio-2-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-3.jpg",
    alt: "photoStudio-3-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-4.jpg",
    alt: "photoStudio-4-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-5.jpg",
    alt: "photoStudio-5-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-6.jpg",
    alt: "photoStudio-6-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-7.jpg",
    alt: "photoStudio-7-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-8.jpg",
    alt: "photoStudio-8-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-9.jpg",
    alt: "photoStudio-9-img",
    width: 1600,
    height: 2161,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-10.jpg",
    alt: "photoStudio-10-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-11.jpg",
    alt: "photoStudio-11-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-12.jpg",
    alt: "photoStudio-12-img",
    width: 5125,
    height: 4000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-13.jpg",
    alt: "photoStudio-13-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-14.jpg",
    alt: "photoStudio-14-img",
    width: 4000,
    height: 6000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-15.jpg",
    alt: "photoStudio-15-img",
    width: 3892,
    height: 6000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-16.jpg",
    alt: "photoStudio-16-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-17.jpg",
    alt: "photoStudio-17-img",
    width: 1600,
    height: 2000,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-18.jpg",
    alt: "photoStudio-18-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-19.jpg",
    alt: "photoStudio-19-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "photoStudio",
    src: "photoStudio/photoStudio-20.jpg",
    alt: "photoStudio-20-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-1.jpg",
    alt: "quinceañera-1-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-2.jpg",
    alt: "quinceañera-2-img",
    width: 1984,
    height: 2976,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-3.jpg",
    alt: "quinceañera-3-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-4.jpg",
    alt: "quinceañera-4-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-5.jpg",
    alt: "quinceañera-5-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-6.jpg",
    alt: "quinceañera-6-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-7.jpg",
    alt: "quinceañera-7-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-8.jpg",
    alt: "quinceañera-8-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-9.jpg",
    alt: "quinceañera-9-img",
    width: 1600,
    height: 2400,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-10.jpg",
    alt: "quinceañera-10-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-11.jpg",
    alt: "quinceañera-11-img",
    width: 1024,
    height: 640,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-12.jpg",
    alt: "quinceañera-12-img",
    width: 2400,
    height: 1600,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-13.jpg",
    alt: "quinceañera-13-img",
    width: 6000,
    height: 4000,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-14.jpg",
    alt: "quinceañera-14-img",
    width: 2976,
    height: 1984,
  },
  {
    category: "quinceañera",
    src: "quinceañera/quinceañera-15.jpg",
    alt: "quinceañera-15-img",
    width: 6000,
    height: 4000,
  },
];

export default portfolioImgData;
